# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      test-input:
        description: 'No manual workflows implemented yet'
        default: 'Kage'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  print_value:
    runs-on: ubuntu-latest
    steps:
    - name: print test variable
      run: echo "Not yet implemented but here is the variable you wrote ${{ github.event.inputs.name }}"